// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddExtensionsClassVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddExtensionsClassVSIXPackageString = "df744805-761f-47f8-9006-deee5dce4ef8";
        public static Guid guidAddExtensionsClassVSIXPackage = new Guid(guidAddExtensionsClassVSIXPackageString);

        public const string guidAddExtensionsClassVSIXPackageCmdSetString = "100a916f-3e38-4d52-8ea9-b5fb58acab25";
        public static Guid guidAddExtensionsClassVSIXPackageCmdSet = new Guid(guidAddExtensionsClassVSIXPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddItemToolWindowCommandId = 0x0100;
    }
}